version: "3"

x-backend: &backend
  build:
    context: .
    dockerfile: deployments/Dockerfile.dev
  environment:
    - REDNOTE_ENV=docker
  volumes:
    - ./:/opt/app
  depends_on:
    rabbit_mq:
      condition: service_healthy
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  rednote:
    <<: *backend
    container_name: rednote
    ports:
      - "8080:8080"
    networks:
      - rednote_network

  worker:
    <<: *backend
    container_name: worker
    command: go run main.go worker
    networks:
      - rednote_network

  postgres:
    image: postgis/postgis:12-3.4-alpine
    platform: linux/amd64
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rednote"]
      interval: 1s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - rednote_network

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - rednote_network

  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 30s
      retries: 3
    networks:
      - rednote_network
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres:
  redis:
  rabbitmq_data:
  rabbitmq_log:
  localstack:

networks:
  rednote_network:
    driver: bridge
