services:
  postgres:
    image: postgis/postgis:12-3.4-alpine
    platform: linux/amd64
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres:
  redis:
